### ISSUE TITLE
로또번호 관리/추천 서비스 프롬프트

### ISSUE THREAD

**Issue by lisyoen** [lisyoen/lotto-client#5]
```yaml
내가 구입했던 로또번호를 입력하면 관리해주고 번호 추천도 해주는 서비스를 개발하려고 해.

제목: 로또번호 관리/추천 서비스
기능: 
- 회원가입/로긴/로그아웃/회원탈퇴
- 로또용지의 QR Code 를 촬영하면 자동으로 등록
- 구입했던 로또번호 조회/당첨결과 조회
- 내가 구입한 번호 통계 조회
- 로또번호 추천 (추후 유료 고려 중)
```

**Comment by lisyoen** [comment]
```yaml
서비스 구성:
- lotto-client: Web
- lotto-server: Node.js, TypeScript, sqlite3
```
